# spring:
#   profiles:
#     active: dev

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file.name: logs/spider.log

browser:
  driver: Chrome
  timeout:
    global: 60
    script: 60
    pageLoad: 60
  cookies:
    name: value


download:
  web-start-url:
    - https://www.ccsh.tp.edu.tw/
  limit-url:
    - https://www.ccsh.tp.edu.tw
  limit-level: 2
  output-local-path: D:\MyDev\git\SeleniumSpider\output
  convert-hyperlink: true
  default-page-name: index.html
  stop-on-fail: false
